name: meshgallery
description: "Just another gallery app."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: "ic_launcher"
  image_path_android: "assets/icons/icon-android.png"
  adaptive_icon_background: "#162023"
  adaptive_icon_foreground: "assets/icons/icon-android.png"

flutter_native_splash:
  color: "#162023"
  image: assets/icons/icon-splash.png
  color_dark: "#162023"
  android_12:
    image: assets/icons/icon-splash-android12.png

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
